export const GET_REFERRALS_REQUEST = 'FETCH_REFERRALS_REQUEST';
export const GET_REFERRALS_SUCCESS = 'FETCH_REFERRALS_SUCCESS';
export const GET_REFERRALS_ERROR = 'FETCH_REFERRALS_ERROR';
export const SAVE_NEW_REFERRAL = 'SAVE_NEW_REFERRAL';
export const SET_EDITING_REFERRAL = 'SET_EDITING_REFERRAL';